export const categories = ['Телефоны','Ноутбуки','Планшеты','Телевизоры'];
export const goods = [{categories: 'Телефоны', brand: 'Apple', price: '1000$', id: 1},
                {categories: 'Телефоны', brand: 'Samsung', price: '1000$', id: 2},
                {categories: 'Телефоны', brand: 'Xiaomi', price: '500$', id: 3},
                {categories: 'Телефоны', brand: 'LG', price: '800$', id: 4},
                {categories: 'Ноутбуки', brand: 'Apple', price: '2000$', id: 5},
                {categories: 'Ноутбуки', brand: 'Samsung', price: '1500$', id: 6},
                {categories: 'Ноутбуки', brand: 'Xiaomi', price: '800$', id: 7},
                {categories: 'Ноутбуки', brand: 'LG', price: '1000$', id: 8},
                {categories: 'Планшеты', brand: 'Apple', price: '800$', id: 9},
                {categories: 'Планшеты', brand: 'Samsung', price: '600$', id: 10},
                {categories: 'Планшеты', brand: 'Xiaomi', price: '300$', id: 11},
                {categories: 'Планшеты', brand: 'LG', price: '500$', id: 12},
                {categories: 'Телевизоры', brand: 'Samsung', price: '1500$', id: 13},
                {categories: 'Телевизоры', brand: 'Xiaomi', price: '800$', id: 14},
                {categories: 'Телевизоры', brand: 'LG', price: '1000$', id: 15}];
export const info = [{categories: 'Телефоны', brand: 'Apple', price: '1000$',color: 'красный', amount: 3, id: 1},
    {categories: 'Телефоны', brand: 'Samsung', price: '1000$', color: 'черный', amount: 3, id: 2},
    {categories: 'Телефоны', brand: 'Xiaomi', price: '500$', color: 'серый', amount: 2, id: 3},
    {categories: 'Телефоны', brand: 'LG', price: '800$', color: 'черный', amount: 9, id: 4},
    {categories: 'Ноутбуки', brand: 'Apple', price: '2000$', color: 'черный', amount: 8, id: 5},
    {categories: 'Ноутбуки', brand: 'Samsung', price: '1500$', color: 'голубой', amount: 7, id: 6},
    {categories: 'Ноутбуки', brand: 'Xiaomi', price: '800$', color: 'серый', amount: 3, id: 7},
    {categories: 'Ноутбуки', brand: 'LG', price: '1000$', color: 'красный', amount: 1, id: 8},
    {categories: 'Планшеты', brand: 'Apple', price: '800$', color: 'черный', amount: 2, id: 9},
    {categories: 'Планшеты', brand: 'Samsung', price: '600$', color: 'серый', amount: 6, id: 10},
    {categories: 'Планшеты', brand: 'Xiaomi', price: '300$', color: 'красный', amount: 5, id: 11},
    {categories: 'Планшеты', brand: 'LG', price: '500$', color: 'голубой', amount: 4, id: 12},
    {categories: 'Телевизоры', brand: 'Samsung', price: '1500$', color: 'серый', amount: 8, id: 13},
    {categories: 'Телевизоры', brand: 'Xiaomi', price: '800$', color: 'красный', amount: 6, id: 14},
    {categories: 'Телевизоры', brand: 'LG', price: '1000$', color: 'черный', amount: 5, id: 15}];